homeassistant:
  name: My Home
  latitude: !secret latitude_coord      # https://www.home-assistant.io/integrations/geo_location/
  longitude: !secret longitude_coord
  elevation: 279
  unit_system: metric
  time_zone: Europe/Moscow

#Вынос во внешние файлы
  customize: !include customize.yaml

#Вынос во внешние файлы
  packages: !include_dir_merge_named includes/packages



# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#Вынос во внешние файлы
proximity: !include includes/proximity.yaml

#recorder: !include includes/recorder.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/bin_sensor

stream: !include_dir_merge_list includes/stream   # Стрим Камер видеонаблюдения
camera:  !include_dir_merge_list includes/stream/camera   # Камеры видеонаблюдения


############################## Configure frontend ##############################
# Тема
frontend:
  themes: !include_dir_merge_named themes
############################# Configure weather ################################
# gismeteo
weather:
  - platform: gismeteo
############################ Configure panel_iframe ############################
panel_iframe:
  configurator:
    title: Конфигуратор
    icon: mdi:square-edit-outline
    url: http://192.168.1.50:3218/
  icons:
    title: Иконки
    icon: mdi:drawing
    url: https://cdn.materialdesignicons.com/4.5.95/
  router:
    title: "Router"
    icon: mdi:access-point
    url: http://192.168.1.1/
############################# Configure http #############################
http:
# sertifikat
  ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey.pem

########################## Configure yandex_smart_home #########################
########################### Configure yandex_station ###########################
# Configure yandex_station
yandex_station:
  username: !secret yandex_station_username
  password: !secret yandex_station_password
  include:
  - Телевизор
  - Телек
  - Сушка
  - Утюг
  - Сервер
  - Принтер

  recognition_lang: ru-RU

conversation:
  intents:
    media_player.yandex_station_###############: [.+]  # замените на вашу станцию
############################ Configure telegram_bot ############################
# https://www.home-assistant.io/integrations/telegram/
# Configure telegram_bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
     - !secret telegram_id_1
     - !secret telegram_id_2
notify:
  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id_1
# Телеграм Вова
  - name: telegram_id_2
    platform: telegram
    chat_id: !secret telegram_id_2

############################## Configure sensor ##############################
###############################  apcupsd ##############################
apcupsd:
#  host: 127.0.0.1
#  port: 3551

########################### Configure binary_sensor ############################
############################### Configure stream ###############################
# Configure stream camera
########################### Configure device_tracker ###########################
# Ping sensors
# когда человек дома подключен к домашнему Wi-Fi
device_tracker:
  - platform: ping
    scan_interval: 30
    count: 4
    consider_home: 120
    hosts:
      ping_vlad: !secret vlad_ip
      ping_admin: !secret admin_ip
      ping_enia: !secret enia_ip

############################## Configure proximity #############################
# https://www.home-assistant.io/integrations/proximity/
######################### Configure mosenergosbyt ##############################
mosenergosbyt:
  username: !secret mosenergosbyt_username
  password: !secret mosenergosbyt_password

# Произвольный формат для лицевых счетов
  account_name: 'Мой супер лицевой счёт'
# Произвольный формат для счётчиков
  meter_name: 'Счётчик жахает'
# Произвольный формат для квитанций
  invoice_name: 'За квитанцию платим много!'

############################# Configure sonoff #################################
sonoff:
 username: !secret sonoff_username
 password: !secret sonoff_password
 mode: cloud

############################# Configure nextcloud ##############################
#nextcloud:
# url:!secret nextcloud_url
# username: !secret nextcloud_username
# password: !secret nextcloud_password

############################# Configure samsungtv ##############################
samsungtv:
  - host: 192.168.1.204





